# -*- coding: utf-8 -*-
"""Tarea4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KrqDZzrG5BLL8uV3XH-aObxioBvR8qSF

# Tarea 4
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cluster import KMeans

# Cargar datos
dataset = pd.read_csv('/content/drive/MyDrive/Inteligencia artificial/Clase 7/Mall_Customers.csv')
X = dataset.iloc[:, [3, 4]].values

print(dataset)
print('')
#plt.plot(X[:,0],X[:,1],'*k')
#plt.xlabel('Ingreso')
#plt.ylabel('Puntuación')
#plt.title('2d example')
#plt.show

"""=============================================================="""

# Ingresando clusters
k=int(input('Ingrese el número de conjuntos deseados: '))
#Generación de centroides aleatorios
kmeans = KMeans(n_clusters=k).fit(X)
#imprimir centroides
y = kmeans.cluster_centers_
print(kmeans.cluster_centers_)
print(kmeans.labels_)
#Graficando datos y centroides iniciales
plt.plot(X[:,0],X[:,1],'*k')
plt.plot(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],'or')
plt.xlabel('Ingreso')
plt.ylabel('Puntuación')
plt.title('centroides aleatorios')
plt.show

"""==============================================================="""